server:
  port: 8080

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/logicea_cards?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=Africa/Nairobi
    username: root
    password: password

jacoco:
  enabled: true
